In [2]:
import pandas as pd

In [3]:
import os
from pathlib import Path

# Locate data file
notebook_dir = Path(".").resolve()
data_path = Path(notebook_dir).parent.parent.parent / "data" / "meta_electronics_2026.jsonl"

print(f"Looking for: {data_path}")
print(f"File exists: {data_path.exists()}")

if data_path.exists():
    # Read JSONL with error handling
    records = []
    errors = 0
    
    with open(data_path, 'r') as f:
        for line_num, line in enumerate(f, 1):
            line = line.strip()
            if not line:  # Skip empty lines
                continue
            try:
                record = pd.read_json(line, typ='series')
                records.append(record)
            except Exception as e:
                errors += 1
                if errors <= 3:  # Show first 3 errors
                    print(f"Line {line_num} error: {str(e)[:80]}")
    
    df = pd.DataFrame(records)
    
    # Sample if needed
    if len(df) > 2000:
        df = df.sample(2000, random_state=42)
    
    print(f"\n✓ Loaded {len(df)} valid records ({errors} skipped)")
    print(f"Columns: {df.columns.tolist()[:5]}...")  # Show first 5 columns
else:
    print("✗ Data file not found")
    df = None

Looking for: /Users/kishorkumarparoi/Desktop/Maven - The AI Engineering Bootcamp /Resources/AIE5-main/21_Rag_Qdrant_Pipeline/data/meta_electronics_2026.jsonl
File exists: True

/var/folders/pw/cff5mdz55nb7ghs1f4rh8f9r0000gn/T/ipykernel_12428/179575653.py:22: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  record = pd.read_json(line, typ='series')
/var/folders/pw/cff5mdz55nb7ghs1f4rh8f9r0000gn/T/ipykernel_12428/179575653.py:22: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  record = pd.read_json(line, typ='series')
/var/folders/pw/cff5mdz55nb7ghs1f4rh8f9r0000gn/T/ipykernel_12428/179575653.py:22: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  record = pd.read_json(line, typ='series')
/var/folders/pw/cff5mdz55nb7ghs1f4rh8f9r0000gn/T/ipykernel_12428/179575653.py:22: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  record = pd.read_json(line, typ='series')
/var/folders/pw/cff5mdz55nb7ghs1f4rh8f9r0000gn/T/ipykernel_12428/179575653.py:22: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  record = pd.read_json(line, typ='series')
/var/folders/pw/cff5mdz55nb7ghs1f4rh8f9r0000gn/T/ipykernel_12428/179575653.py:22: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  record = pd.read_json(line, typ='series')
/var/folders/pw/cff5mdz55nb7ghs1f4rh8f9r0000gn/T/ipykernel_12428/179575653.py:22: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  record = pd.read_json(line, typ='series')
/var/folders/pw/cff5mdz55nb7ghs1f4rh8f9r0000gn/T/ipykernel_12428/179575653.py:22: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  record = pd.read_json(line, typ='series')
/var/folders/pw/cff5mdz55nb7ghs1f4rh8f9r0000gn/T/ipykernel_12428/179575653.py:22: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  record = pd.read_json(line, typ='series')
/var/folders/pw/cff5mdz55nb7ghs1f4rh8f9r0000gn/T/ipykernel_12428/179575653.py:22: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  record = pd.read_json(line, typ='series')
/var/folders/pw/cff5mdz55nb7ghs1f4rh8f9r0000gn/T/ipykernel_12428/179575653.py:22: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  record = pd.read_json(line, typ='series')
/var/folders/pw/cff5mdz55nb7ghs1f4rh8f9r0000gn/T/ipykernel_12428/179575653.py:22: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  record = pd.read_json(line, typ='series')
/var/folders/pw/cff5mdz55nb7ghs1f4rh8f9r0000gn/T/ipykernel_12428/179575653.py:22: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  record = pd.read_json(line, typ='series')
/var/folders/pw/cff5mdz55nb7ghs1f4rh8f9r0000gn/T/ipykernel_12428/179575653.py:22: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  record = pd.read_json(line, typ='series')
/var/folders/pw/cff5mdz55nb7ghs1f4rh8f9r0000gn/T/ipykernel_12428/179575653.py:22: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  record = pd.read_json(line, typ='series')
/var/folders/pw/cff5mdz55nb7ghs1f4rh8f9r0000gn/T/ipykernel_12428/179575653.py:22: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  record = pd.read_json(line, typ='series')
/var/folders/pw/cff5mdz55nb7ghs1f4rh8f9r0000gn/T/ipykernel_12428/179575653.py:22: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  record = pd.read_json(line, typ='series')
/var/folders/pw/cff5mdz55nb7ghs1f4rh8f9r0000gn/T/ipykernel_12428/179575653.py:22: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  record = pd.read_json(line, typ='series')
/var/folders/pw/cff5mdz55nb7ghs1f4rh8f9r0000gn/T/ipykernel_12428/179575653.py:22: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  record = pd.read_json(line, typ='series')
/var/folders/pw/cff5mdz55nb7ghs1f4rh8f9r0000gn/T/ipykernel_12428/179575653.py:22: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  record = pd.read_json(line, typ='series')
/var/folders/pw/cff5mdz55nb7ghs1f4rh8f9r0000gn/T/ipykernel_12428/179575653.py:22: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  record = pd.read_json(line, typ='series')
/var/folders/pw/cff5mdz55nb7ghs1f4rh8f9r0000gn/T/ipykernel_12428/179575653.py:22: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  record = pd.read_json(line, typ='series')
/var/folders/pw/cff5mdz55nb7ghs1f4rh8f9r0000gn/T/ipykernel_12428/179575653.py:22: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  record = pd.read_json(line, typ='series')
/var/folders/pw/cff5mdz55nb7ghs1f4rh8f9r0000gn/T/ipykernel_12428/179575653.py:22: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  record = pd.read_json(line, typ='series')
/var/folders/pw/cff5mdz55nb7ghs1f4rh8f9r0000gn/T/ipykernel_12428/179575653.py:22: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  record = pd.read_json(line, typ='series')
/var/folders/pw/cff5mdz55nb7ghs1f4rh8f9r0000gn/T/ipykernel_12428/179575653.py:22: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  record = pd.read_json(line, typ='series')
/var/folders/pw/cff5mdz55nb7ghs1f4rh8f9r0000gn/T/ipykernel_12428/179575653.py:22: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  record = pd.read_json(line, typ='series')
/var/folders/pw/cff5mdz55nb7ghs1f4rh8f9r0000gn/T/ipykernel_12428/179575653.py:22: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  record = pd.read_json(line, typ='series')
/var/folders/pw/cff5mdz55nb7ghs1f4rh8f9r0000gn/T/ipykernel_12428/179575653.py:22: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  record = pd.read_json(line, typ='series')
/var/folders/pw/cff5mdz55nb7ghs1f4rh8f9r0000gn/T/ipykernel_12428/179575653.py:22: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  record = pd.read_json(line, typ='series')
/var/folders/pw/cff5mdz55nb7ghs1f4rh8f9r0000gn/T/ipykernel_12428/179575653.py:22: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  record = pd.read_json(line, typ='series')
/var/folders/pw/cff5mdz55nb7ghs1f4rh8f9r0000gn/T/ipykernel_12428/179575653.py:22: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  record = pd.read_json(line, typ='series')
/var/folders/pw/cff5mdz55nb7ghs1f4rh8f9r0000gn/T/ipykernel_12428/179575653.py:22: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  record = pd.read_json(line, typ='series')
/var/folders/pw/cff5mdz55nb7ghs1f4rh8f9r0000gn/T/ipykernel_12428/179575653.py:22: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  record = pd.read_json(line, typ='series')
/var/folders/pw/cff5mdz55nb7ghs1f4rh8f9r0000gn/T/ipykernel_12428/179575653.py:22: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  record = pd.read_json(line, typ='series')
/var/folders/pw/cff5mdz55nb7ghs1f4rh8f9r0000gn/T/ipykernel_12428/179575653.py:22: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  record = pd.read_json(line, typ='series')
/var/folders/pw/cff5mdz55nb7ghs1f4rh8f9r0000gn/T/ipykernel_12428/179575653.py:22: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  record = pd.read_json(line, typ='series')
/var/folders/pw/cff5mdz55nb7ghs1f4rh8f9r0000gn/T/ipykernel_12428/179575653.py:22: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  record = pd.read_json(line, typ='series')
/var/folders/pw/cff5mdz55nb7ghs1f4rh8f9r0000gn/T/ipykernel_12428/179575653.py:22: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  record = pd.read_json(line, typ='series')
/var/folders/pw/cff5mdz55nb7ghs1f4rh8f9r0000gn/T/ipykernel_12428/179575653.py:22: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  record = pd.read_json(line, typ='series')
/var/folders/pw/cff5mdz55nb7ghs1f4rh8f9r0000gn/T/ipykernel_12428/179575653.py:22: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  record = pd.read_json(line, typ='series')
/var/folders/pw/cff5mdz55nb7ghs1f4rh8f9r0000gn/T/ipykernel_12428/179575653.py:22: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  record = pd.read_json(line, typ='series')
/var/folders/pw/cff5mdz55nb7ghs1f4rh8f9r0000gn/T/ipykernel_12428/179575653.py:22: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  record = pd.read_json(line, typ='series')
/var/folders/pw/cff5mdz55nb7ghs1f4rh8f9r0000gn/T/ipykernel_12428/179575653.py:22: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  record = pd.read_json(line, typ='series')
/var/folders/pw/cff5mdz55nb7ghs1f4rh8f9r0000gn/T/ipykernel_12428/179575653.py:22: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  record = pd.read_json(line, typ='series')
/var/folders/pw/cff5mdz55nb7ghs1f4rh8f9r0000gn/T/ipykernel_12428/179575653.py:22: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  record = pd.read_json(line, typ='series')
/var/folders/pw/cff5mdz55nb7ghs1f4rh8f9r0000gn/T/ipykernel_12428/179575653.py:22: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  record = pd.read_json(line, typ='series')
/var/folders/pw/cff5mdz55nb7ghs1f4rh8f9r0000gn/T/ipykernel_12428/179575653.py:22: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  record = pd.read_json(line, typ='series')
/var/folders/pw/cff5mdz55nb7ghs1f4rh8f9r0000gn/T/ipykernel_12428/179575653.py:22: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  record = pd.read_json(line, typ='series')
/var/folders/pw/cff5mdz55nb7ghs1f4rh8f9r0000gn/T/ipykernel_12428/179575653.py:22: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  record = pd.read_json(line, typ='series')
/var/folders/pw/cff5mdz55nb7ghs1f4rh8f9r0000gn/T/ipykernel_12428/179575653.py:22: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  record = pd.read_json(line, typ='series')
/var/folders/pw/cff5mdz55nb7ghs1f4rh8f9r0000gn/T/ipykernel_12428/179575653.py:22: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  record = pd.read_json(line, typ='series')
/var/folders/pw/cff5mdz55nb7ghs1f4rh8f9r0000gn/T/ipykernel_12428/179575653.py:22: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  record = pd.read_json(line, typ='series')
/var/folders/pw/cff5mdz55nb7ghs1f4rh8f9r0000gn/T/ipykernel_12428/179575653.py:22: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  record = pd.read_json(line, typ='series')
/var/folders/pw/cff5mdz55nb7ghs1f4rh8f9r0000gn/T/ipykernel_12428/179575653.py:22: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  record = pd.read_json(line, typ='series')
/var/folders/pw/cff5mdz55nb7ghs1f4rh8f9r0000gn/T/ipykernel_12428/179575653.py:22: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  record = pd.read_json(line, typ='series')
/var/folders/pw/cff5mdz55nb7ghs1f4rh8f9r0000gn/T/ipykernel_12428/179575653.py:22: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  record = pd.read_json(line, typ='series')
/var/folders/pw/cff5mdz55nb7ghs1f4rh8f9r0000gn/T/ipykernel_12428/179575653.py:22: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  record = pd.read_json(line, typ='series')
/var/folders/pw/cff5mdz55nb7ghs1f4rh8f9r0000gn/T/ipykernel_12428/179575653.py:22: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  record = pd.read_json(line, typ='series')
/var/folders/pw/cff5mdz55nb7ghs1f4rh8f9r0000gn/T/ipykernel_12428/179575653.py:22: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  record = pd.read_json(line, typ='series')
/var/folders/pw/cff5mdz55nb7ghs1f4rh8f9r0000gn/T/ipykernel_12428/179575653.py:22: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  record = pd.read_json(line, typ='series')
/var/folders/pw/cff5mdz55nb7ghs1f4rh8f9r0000gn/T/ipykernel_12428/179575653.py:22: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  record = pd.read_json(line, typ='series')
/var/folders/pw/cff5mdz55nb7ghs1f4rh8f9r0000gn/T/ipykernel_12428/179575653.py:22: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  record = pd.read_json(line, typ='series')
/var/folders/pw/cff5mdz55nb7ghs1f4rh8f9r0000gn/T/ipykernel_12428/179575653.py:22: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  record = pd.read_json(line, typ='series')
/var/folders/pw/cff5mdz55nb7ghs1f4rh8f9r0000gn/T/ipykernel_12428/179575653.py:22: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  record = pd.read_json(line, typ='series')
/var/folders/pw/cff5mdz55nb7ghs1f4rh8f9r0000gn/T/ipykernel_12428/179575653.py:22: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  record = pd.read_json(line, typ='series')
/var/folders/pw/cff5mdz55nb7ghs1f4rh8f9r0000gn/T/ipykernel_12428/179575653.py:22: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  record = pd.read_json(line, typ='series')

✓ Loaded 2000 valid records (0 skipped)
Columns: ['main_category', 'title', 'average_rating', 'rating_number', 'features']...

/var/folders/pw/cff5mdz55nb7ghs1f4rh8f9r0000gn/T/ipykernel_12428/179575653.py:22: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  record = pd.read_json(line, typ='series')
/var/folders/pw/cff5mdz55nb7ghs1f4rh8f9r0000gn/T/ipykernel_12428/179575653.py:22: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  record = pd.read_json(line, typ='series')
/var/folders/pw/cff5mdz55nb7ghs1f4rh8f9r0000gn/T/ipykernel_12428/179575653.py:22: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  record = pd.read_json(line, typ='series')
/var/folders/pw/cff5mdz55nb7ghs1f4rh8f9r0000gn/T/ipykernel_12428/179575653.py:22: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  record = pd.read_json(line, typ='series')
/var/folders/pw/cff5mdz55nb7ghs1f4rh8f9r0000gn/T/ipykernel_12428/179575653.py:22: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  record = pd.read_json(line, typ='series')
/var/folders/pw/cff5mdz55nb7ghs1f4rh8f9r0000gn/T/ipykernel_12428/179575653.py:22: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  record = pd.read_json(line, typ='series')
/var/folders/pw/cff5mdz55nb7ghs1f4rh8f9r0000gn/T/ipykernel_12428/179575653.py:22: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  record = pd.read_json(line, typ='series')
/var/folders/pw/cff5mdz55nb7ghs1f4rh8f9r0000gn/T/ipykernel_12428/179575653.py:22: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  record = pd.read_json(line, typ='series')
/var/folders/pw/cff5mdz55nb7ghs1f4rh8f9r0000gn/T/ipykernel_12428/179575653.py:22: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  record = pd.read_json(line, typ='series')
/var/folders/pw/cff5mdz55nb7ghs1f4rh8f9r0000gn/T/ipykernel_12428/179575653.py:22: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  record = pd.read_json(line, typ='series')
/var/folders/pw/cff5mdz55nb7ghs1f4rh8f9r0000gn/T/ipykernel_12428/179575653.py:22: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  record = pd.read_json(line, typ='series')
/var/folders/pw/cff5mdz55nb7ghs1f4rh8f9r0000gn/T/ipykernel_12428/179575653.py:22: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  record = pd.read_json(line, typ='series')
/var/folders/pw/cff5mdz55nb7ghs1f4rh8f9r0000gn/T/ipykernel_12428/179575653.py:22: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  record = pd.read_json(line, typ='series')
/var/folders/pw/cff5mdz55nb7ghs1f4rh8f9r0000gn/T/ipykernel_12428/179575653.py:22: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  record = pd.read_json(line, typ='series')
/var/folders/pw/cff5mdz55nb7ghs1f4rh8f9r0000gn/T/ipykernel_12428/179575653.py:22: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  record = pd.read_json(line, typ='series')
/var/folders/pw/cff5mdz55nb7ghs1f4rh8f9r0000gn/T/ipykernel_12428/179575653.py:22: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  record = pd.read_json(line, typ='series')
/var/folders/pw/cff5mdz55nb7ghs1f4rh8f9r0000gn/T/ipykernel_12428/179575653.py:22: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  record = pd.read_json(line, typ='series')
/var/folders/pw/cff5mdz55nb7ghs1f4rh8f9r0000gn/T/ipykernel_12428/179575653.py:22: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  record = pd.read_json(line, typ='series')
/var/folders/pw/cff5mdz55nb7ghs1f4rh8f9r0000gn/T/ipykernel_12428/179575653.py:22: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  record = pd.read_json(line, typ='series')
/var/folders/pw/cff5mdz55nb7ghs1f4rh8f9r0000gn/T/ipykernel_12428/179575653.py:22: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  record = pd.read_json(line, typ='series')
/var/folders/pw/cff5mdz55nb7ghs1f4rh8f9r0000gn/T/ipykernel_12428/179575653.py:22: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  record = pd.read_json(line, typ='series')
/var/folders/pw/cff5mdz55nb7ghs1f4rh8f9r0000gn/T/ipykernel_12428/179575653.py:22: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  record = pd.read_json(line, typ='series')
/var/folders/pw/cff5mdz55nb7ghs1f4rh8f9r0000gn/T/ipykernel_12428/179575653.py:22: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  record = pd.read_json(line, typ='series')
/var/folders/pw/cff5mdz55nb7ghs1f4rh8f9r0000gn/T/ipykernel_12428/179575653.py:22: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  record = pd.read_json(line, typ='series')
/var/folders/pw/cff5mdz55nb7ghs1f4rh8f9r0000gn/T/ipykernel_12428/179575653.py:22: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  record = pd.read_json(line, typ='series')
/var/folders/pw/cff5mdz55nb7ghs1f4rh8f9r0000gn/T/ipykernel_12428/179575653.py:22: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  record = pd.read_json(line, typ='series')
/var/folders/pw/cff5mdz55nb7ghs1f4rh8f9r0000gn/T/ipykernel_12428/179575653.py:22: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  record = pd.read_json(line, typ='series')
/var/folders/pw/cff5mdz55nb7ghs1f4rh8f9r0000gn/T/ipykernel_12428/179575653.py:22: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  record = pd.read_json(line, typ='series')
/var/folders/pw/cff5mdz55nb7ghs1f4rh8f9r0000gn/T/ipykernel_12428/179575653.py:22: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  record = pd.read_json(line, typ='series')
/var/folders/pw/cff5mdz55nb7ghs1f4rh8f9r0000gn/T/ipykernel_12428/179575653.py:22: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  record = pd.read_json(line, typ='series')
/var/folders/pw/cff5mdz55nb7ghs1f4rh8f9r0000gn/T/ipykernel_12428/179575653.py:22: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  record = pd.read_json(line, typ='series')
/var/folders/pw/cff5mdz55nb7ghs1f4rh8f9r0000gn/T/ipykernel_12428/179575653.py:22: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  record = pd.read_json(line, typ='series')
/var/folders/pw/cff5mdz55nb7ghs1f4rh8f9r0000gn/T/ipykernel_12428/179575653.py:22: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  record = pd.read_json(line, typ='series')
/var/folders/pw/cff5mdz55nb7ghs1f4rh8f9r0000gn/T/ipykernel_12428/179575653.py:22: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  record = pd.read_json(line, typ='series')
/var/folders/pw/cff5mdz55nb7ghs1f4rh8f9r0000gn/T/ipykernel_12428/179575653.py:22: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  record = pd.read_json(line, typ='series')
/var/folders/pw/cff5mdz55nb7ghs1f4rh8f9r0000gn/T/ipykernel_12428/179575653.py:22: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  record = pd.read_json(line, typ='series')
/var/folders/pw/cff5mdz55nb7ghs1f4rh8f9r0000gn/T/ipykernel_12428/179575653.py:22: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  record = pd.read_json(line, typ='series')
/var/folders/pw/cff5mdz55nb7ghs1f4rh8f9r0000gn/T/ipykernel_12428/179575653.py:22: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  record = pd.read_json(line, typ='series')
/var/folders/pw/cff5mdz55nb7ghs1f4rh8f9r0000gn/T/ipykernel_12428/179575653.py:22: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  record = pd.read_json(line, typ='series')
/var/folders/pw/cff5mdz55nb7ghs1f4rh8f9r0000gn/T/ipykernel_12428/179575653.py:22: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  record = pd.read_json(line, typ='series')
/var/folders/pw/cff5mdz55nb7ghs1f4rh8f9r0000gn/T/ipykernel_12428/179575653.py:22: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  record = pd.read_json(line, typ='series')
/var/folders/pw/cff5mdz55nb7ghs1f4rh8f9r0000gn/T/ipykernel_12428/179575653.py:22: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  record = pd.read_json(line, typ='series')
/var/folders/pw/cff5mdz55nb7ghs1f4rh8f9r0000gn/T/ipykernel_12428/179575653.py:22: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  record = pd.read_json(line, typ='series')
/var/folders/pw/cff5mdz55nb7ghs1f4rh8f9r0000gn/T/ipykernel_12428/179575653.py:22: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  record = pd.read_json(line, typ='series')
/var/folders/pw/cff5mdz55nb7ghs1f4rh8f9r0000gn/T/ipykernel_12428/179575653.py:22: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  record = pd.read_json(line, typ='series')
/var/folders/pw/cff5mdz55nb7ghs1f4rh8f9r0000gn/T/ipykernel_12428/179575653.py:22: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  record = pd.read_json(line, typ='series')
/var/folders/pw/cff5mdz55nb7ghs1f4rh8f9r0000gn/T/ipykernel_12428/179575653.py:22: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  record = pd.read_json(line, typ='series')
/var/folders/pw/cff5mdz55nb7ghs1f4rh8f9r0000gn/T/ipykernel_12428/179575653.py:22: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  record = pd.read_json(line, typ='series')
/var/folders/pw/cff5mdz55nb7ghs1f4rh8f9r0000gn/T/ipykernel_12428/179575653.py:22: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  record = pd.read_json(line, typ='series')
/var/folders/pw/cff5mdz55nb7ghs1f4rh8f9r0000gn/T/ipykernel_12428/179575653.py:22: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  record = pd.read_json(line, typ='series')
/var/folders/pw/cff5mdz55nb7ghs1f4rh8f9r0000gn/T/ipykernel_12428/179575653.py:22: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  record = pd.read_json(line, typ='series')
/var/folders/pw/cff5mdz55nb7ghs1f4rh8f9r0000gn/T/ipykernel_12428/179575653.py:22: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  record = pd.read_json(line, typ='series')
/var/folders/pw/cff5mdz55nb7ghs1f4rh8f9r0000gn/T/ipykernel_12428/179575653.py:22: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  record = pd.read_json(line, typ='series')
/var/folders/pw/cff5mdz55nb7ghs1f4rh8f9r0000gn/T/ipykernel_12428/179575653.py:22: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  record = pd.read_json(line, typ='series')
/var/folders/pw/cff5mdz55nb7ghs1f4rh8f9r0000gn/T/ipykernel_12428/179575653.py:22: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  record = pd.read_json(line, typ='series')
/var/folders/pw/cff5mdz55nb7ghs1f4rh8f9r0000gn/T/ipykernel_12428/179575653.py:22: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  record = pd.read_json(line, typ='series')
/var/folders/pw/cff5mdz55nb7ghs1f4rh8f9r0000gn/T/ipykernel_12428/179575653.py:22: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  record = pd.read_json(line, typ='series')
/var/folders/pw/cff5mdz55nb7ghs1f4rh8f9r0000gn/T/ipykernel_12428/179575653.py:22: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  record = pd.read_json(line, typ='series')
/var/folders/pw/cff5mdz55nb7ghs1f4rh8f9r0000gn/T/ipykernel_12428/179575653.py:22: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  record = pd.read_json(line, typ='series')
/var/folders/pw/cff5mdz55nb7ghs1f4rh8f9r0000gn/T/ipykernel_12428/179575653.py:22: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  record = pd.read_json(line, typ='series')
/var/folders/pw/cff5mdz55nb7ghs1f4rh8f9r0000gn/T/ipykernel_12428/179575653.py:22: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  record = pd.read_json(line, typ='series')
/var/folders/pw/cff5mdz55nb7ghs1f4rh8f9r0000gn/T/ipykernel_12428/179575653.py:22: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  record = pd.read_json(line, typ='series')
/var/folders/pw/cff5mdz55nb7ghs1f4rh8f9r0000gn/T/ipykernel_12428/179575653.py:22: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  record = pd.read_json(line, typ='series')
/var/folders/pw/cff5mdz55nb7ghs1f4rh8f9r0000gn/T/ipykernel_12428/179575653.py:22: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  record = pd.read_json(line, typ='series')
/var/folders/pw/cff5mdz55nb7ghs1f4rh8f9r0000gn/T/ipykernel_12428/179575653.py:22: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  record = pd.read_json(line, typ='series')
/var/folders/pw/cff5mdz55nb7ghs1f4rh8f9r0000gn/T/ipykernel_12428/179575653.py:22: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  record = pd.read_json(line, typ='series')
/var/folders/pw/cff5mdz55nb7ghs1f4rh8f9r0000gn/T/ipykernel_12428/179575653.py:22: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  record = pd.read_json(line, typ='series')

In [4]:
df.head()

,main_category,title,average_rating,rating_number,features,description,price,images,videos,store,categories,details,parent_asin,bought_together,subtitle,author
1284,Computers,Ingooood Wooden Jigsaw Puzzle - Zodiac Horosco...,4.7,30,[],[],NaN,[{'thumb': 'https://m.media-amazon.com/images/...,"[{'title': 'Cute LITTLE wood puzzle', 'url': '...",Ingooood,[],{'Package Dimensions': '8.19 x 6.46 x 1.93 inc...,B08QHF495C,None,NaN,NaN
982,Computers,Bfun Union Jack Flag Silicone MacBook Pro Keyb...,3.5,2,[],[],NaN,[{'thumb': 'https://m.media-amazon.com/images/...,[],None,"[Electronics, Computers & Accessories, Laptop ...","{'Item Weight': '0.639 ounces', 'Package Dimen...",B016RY6FE2,None,NaN,NaN
1542,Camera & Photo,"CKK 【Upgraded 3MP】 PTZ Camera Outdoor, 3MP Wir...",4.1,344,[【AI Human Detection with Floodlight and Siren...,[],59.99,[{'thumb': 'https://m.media-amazon.com/images/...,[{'title': 'Wireless Outdoor 360 1080P Securit...,CKK,"[Electronics, Camera & Photo, Video Surveillan...",{'Product Dimensions': '8.07 x 6.49 x 8.26 inc...,B09FSWNTLF,None,NaN,NaN
593,Portable Audio & Accessories,"iPhone 6S Plus Case, Rock Classic Shell Hybrid...",4.1,8,[],[],NaN,[{'thumb': 'https://m.media-amazon.com/images/...,[],ROCK,[],"{'Item Weight': '1 ounces', 'Product Dimension...",B016OE0MTY,None,NaN,NaN
1292,Computers,KIQ Shockproof Heavy Duty Impact Drop Protecti...,3.9,370,[Perfect fit for theLG G PAD X 8.0 or LG G PAD...,[],NaN,[{'thumb': 'https://m.media-amazon.com/images/...,[],KIQ,"[Electronics, Computers & Accessories, Tablet ...","{'Standing screen display size': '8 Inches', '...",B01LYSVG0C,None,NaN,NaN

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2000 entries, 1284 to 805
Data columns (total 16 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   main_category    1974 non-null   object
 1   title            2000 non-null   object
 2   average_rating   2000 non-null   float64
 3   rating_number    2000 non-null   int64
 4   features         2000 non-null   object
 5   description      2000 non-null   object
 6   price            852 non-null    float64
 7   images           2000 non-null   object
 8   videos           2000 non-null   object
 9   store            1987 non-null   object
 10  categories       2000 non-null   object
 11  details          2000 non-null   object
 12  parent_asin      2000 non-null   object
 13  bought_together  0 non-null      object
 14  subtitle         1 non-null      object
 15  author           0 non-null      float64
dtypes: float64(3), int64(1), object(12)
memory usage: 265.6+ KB

In [6]:
electronics_df = pd.read_json("../../../data/Electronics_100mb.jsonl", lines=True)

In [7]:
electronics_df

,rating,title,text,images,asin,parent_asin,user_id,timestamp,helpful_vote,verified_purchase
0,3,Smells like gasoline! Going back!,First & most offensive: they reek of gasoline ...,[{'small_image_url': 'https://m.media-amazon.c...,B083NRGZMM,B083NRGZMM,AFKZENTNBQ7A7V7UXW5JJI6UGRYQ,2022-07-18 22:58:37.948,0,True
1,1,Didn’t work at all lenses loose/broken.,These didn’t work. Idk if they were damaged in...,[],B07N69T6TM,B07N69T6TM,AFKZENTNBQ7A7V7UXW5JJI6UGRYQ,2020-06-20 18:42:29.731,0,True
2,5,Excellent!,I love these. They even come with a carry case...,[],B01G8JO5F2,B01G8JO5F2,AFKZENTNBQ7A7V7UXW5JJI6UGRYQ,2018-04-07 09:23:37.534,0,True
3,5,Great laptop backpack!,I was searching for a sturdy backpack for scho...,[],B001OC5JKY,B001OC5JKY,AGGZ357AO26RQZVRLGU4D4N52DZQ,2010-11-20 18:41:35.000,18,True
4,5,Best Headphones in the Fifties price range!,I've bought these headphones three times becau...,[],B013J7WUGC,B07CJYMRWM,AG2L7H23R5LLKDKLBEF2Q3L2MVDA,2023-02-17 02:39:41.238,0,True
...,...,...,...,...,...,...,...,...,...,...
160334,2,"Doesn’t fray, but stops charging","Cables don’t fray, but the they stopped chargi...",[],B0785DTFF4,B0C862H1P7,AFDROHRSLDOWFMD5KXFCKR2MSWOQ,2021-04-03 00:20:45.398,0,True
160335,5,Another hit from Skullcandy,I’ve always been a fan of Skullcandy and have ...,[],B07R1Q1Z75,B07YYWM2LN,AFDROHRSLDOWFMD5KXFCKR2MSWOQ,2020-02-25 21:04:10.998,0,True
160336,2,What a dud!,I bought this set-up along with the D-Link DHP...,[],B005PAIZES,B005PAIZES,AFDROHRSLDOWFMD5KXFCKR2MSWOQ,2015-11-05 01:00:34.000,0,True
160337,5,These are great!,I have four of these and they get the job done!,[],B00D1IUEHW,B00D1IUEHW,AFDROHRSLDOWFMD5KXFCKR2MSWOQ,2015-03-30 13:02:44.000,0,True
160338,5,video card is GREAT,Got this to replace a little cheap video card ...,[],B00J01IVQU,B00J01IVQU,AFDROHRSLDOWFMD5KXFCKR2MSWOQ,2015-03-30 13:02:15.000,1,True

In [8]:
electronics_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 160339 entries, 0 to 160338
Data columns (total 10 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   rating             160339 non-null  int64
 1   title              160339 non-null  object
 2   text               160339 non-null  object
 3   images             160339 non-null  object
 4   asin               160339 non-null  object
 5   parent_asin        160339 non-null  object
 6   user_id            160339 non-null  object
 7   timestamp          160339 non-null  datetime64[ns]
 8   helpful_vote       160339 non-null  int64
 9   verified_purchase  160339 non-null  bool
dtypes: bool(1), datetime64[ns](1), int64(2), object(6)
memory usage: 11.2+ MB